# Copy is not required. Use ./scripts/init_vault.sh to create encrypted:
# ansible/group_vars/all/vault.yml
#
# This value is used by Ansible as the sudo password on remote client nodes.
ansible_become_password: "CHANGE_ME"
