# Копировать этот файл не нужно. Используй ./scripts/init_vault.sh, чтобы создать зашифрованный:
# ansible/group_vars/all/vault.yml
#
# Это значение Ansible использует как sudo-пароль на удалённых клиентских узлах.
ansible_become_password: "CHANGE_ME"
